name: Code Quality

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "2.7"
      - name: Run flake8
        uses: julianwachholz/flake8-action@v1
        with:
          checkName: "Python Lint"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
